version: "3.9"
services:
  #Para que esto corra creo que falta el dockerfile
  #myserver:
  #build: .
  #ports:
  #  - "3000:3000"
  #links:
  #  - postgy
  #volumes:
  #  - .:/home/app
  # - /home/app
  mi-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: ricardo
      POSTGRES_DB: campana
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
